@startuml UC_AbsensiGajiGuru
title Diagram Use Case untuk Sistem Absensi dan Gaji Guru

actor "Admin" as admin
actor "Staf" as staf
actor "Guru" as guru

rectangle "Sistem Absensi & Gaji Guru" {
    usecase "Mencatat Kehadiran Guru" as UC_MencatatKehadiran
    usecase "Mengelola Data Guru" as UC_MengelolaDataGuru
    usecase "Melihat Kehadiran Guru" as UC_MelihatKehadiran
    usecase "Melihat Riwayat Gaji" as UC_MelihatRiwayatGaji
    usecase "Memperbarui Kehadiran Guru" as UC_MemperbaruiKehadiran
    usecase "Memperbarui Gaji Guru" as UC_MemperbaruiGaji
    usecase "Menyetujui Pembayaran Gaji" as UC_MenyetujuiPembayaranGaji
    usecase "Menyiapkan Slip Gaji" as UC_MenyiapkanSlipGaji
    usecase "Mencatat Kehadiran" as UC_MencatatKehadiran

    guru --> UC_MencatatKehadiran
    guru --> UC_MelihatKehadiran
    guru --> UC_MelihatRiwayatGaji

    staf --> UC_MencatatKehadiran
    staf --> UC_MemperbaruiKehadiran
    staf --> UC_MenyiapkanSlipGaji
    staf --> UC_MelihatRiwayatGaji

    admin --> UC_MengelolaDataGuru
    admin --> UC_MenyetujuiPembayaranGaji
    admin --> UC_MemperbaruiGaji
    admin --> UC_MenyiapkanSlipGaji
}

@enduml
