@startuml Flow_AbsensiGajiGuru
title Alur Proses Absensi dan Gaji Guru

|Guru|
start
:Catat Kehadiran;
:Periksa Riwayat Kehadiran;
:Periksa Riwayat Gaji;

|Staf|
:Catat Kehadiran Guru;
:Verifikasi Kehadiran Guru;
:Perbarui Kehadiran Guru;
:Perbarui Data Gaji Guru;
:Siapkan Slip Gaji;

|Admin|
:Kelola Data Guru;
:Verifikasi Kehadiran Guru;
:Perbarui Data Kehadiran;
:Perbarui Data Gaji;
:Tinjau dan Setujui Pembayaran Gaji;
:Proses Penyetoran Gaji;

|Admin/Staff|
if (Pembayaran Gaji Disetujui?) then (ya)
    :Pembayaran Gaji Terselesaikan;
    :Perbarui Status Pembayaran;
else (tidak)
    :Batalkan Pembayaran Gaji;
    stop
endif

|Guru|
:Terima Slip Gaji;
:Verifikasi Pembayaran Gaji;
stop
@enduml
