@startuml Flow_AbsensiGajiGuru
title Business Flow for Absensi dan Gaji Guru System

|Guru|
start
:Catat Kehadiran;
:Verifikasi Kehadiran;
:Periksa Riwayat Kehadiran;
:Periksa Riwayat Gaji;
stop

|Staf|
start
:Catat Kehadiran Guru;
:Verifikasi Kehadiran Guru;
:Perbarui Kehadiran Guru;
:Hasilkan Slip Gaji;
:Periksa Riwayat Gaji Guru;
stop

|Admin|
start
:Kelola Data Guru;
:Perbarui Data Kehadiran;
:Perbarui Data Gaji;
:Tinjau dan Setujui Pembayaran Gaji;
:Periksa Laporan Absensi dan Gaji;
:Verifikasi Laporan;
:Penyetoran Gaji;
stop

|Admin/Staff|
if (Pembayaran Gaji Disetujui?) then (ya)
    :Pembayaran Gaji Terselesaikan;
    :Perbarui Status Pembayaran;
else (tidak)
    :Batalkan Pembayaran Gaji;
    stop
endif

@enduml
